apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventer-server
  namespace: eventer-demo
  labels:
    app: eventer-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventer-server
  template:
    metadata:
      labels:
        app: eventer-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
      - name: server
        image: quay.io/mchirico/admission-controller-eventer-demo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: eventer-api
        volumeMounts:
        - name: eventer-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: eventer-tls-certs
        secret:
          secretName: eventer-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: eventer-server
  namespace: eventer-demo
spec:
  selector:
    app: eventer-server
  ports:
    - port: 443
      targetPort: eventer-api
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingeventerConfiguration
metadata:
  name: demo-eventer
eventers:
  - name: eventer-server.eventer-demo.svc
    clientConfig:
      service:
        name: eventer-server
        namespace: eventer-demo
        path: "/mutate"
      caBundle: QmFnIEF0dHJpYnV0ZXMKICAgIGxvY2FsS2V5SUQ6IEVBIEJGIDE5IEZBIDg0IEM4IEEwIEUyIDk0IDAzIDUyIDVEIDQ0IEJBIDlDIDk4IEVGIDczIDE4IDIwIApzdWJqZWN0PS9DTj13ZWJob29rLXNlcnZlci53ZWJob29rLWRlbW8uc3ZjL089Y2xpZW50Cmlzc3Vlcj0vQ049VExTR2VuU2VsZlNpZ25lZHRSb290Q0EvTD0kJCQkCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVlRDQ0FqMmdBd0lCQWdJQkFqQU5CZ2txaGtpRzl3MEJBUXNGQURBeE1TQXdIZ1lEVlFRRERCZFVURk5IClpXNVRaV3htVTJsbmJtVmtkRkp2YjNSRFFURU5NQXNHQTFVRUJ3d0VKQ1FrSkRBZUZ3MHlNREE1TVRVeU1UQXgKTWpGYUZ3MHpNREE1TVRNeU1UQXhNakZhTURzeEtEQW1CZ05WQkFNTUgzZGxZbWh2YjJzdGMyVnlkbVZ5TG5kbApZbWh2YjJzdFpHVnRieTV6ZG1NeER6QU5CZ05WQkFvTUJtTnNhV1Z1ZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5tNTJHa3Z1ZmtaOWhOR1V2VHpkYURJR2txTVAvSmtlNWppazlweWFzU3IKcXVYSHFBZndJckRiWklNTW9tVTZUVTRQWmd0cjFjTzB1eXZqbUczK1JkVU1GcGlpTlpJcnlLVzUrMXZtaXhlZgpmbWUzN2J5MnFybnIxcHl4QVBJaGVCTVNsTkIwWXB4L0wrc3l6VG9yMUdadWlWZzV2cFdsNDRYQUhvL2pGRkhTCmpEN1ZQMng0T3FQSndZb3ZJVGVTRWlzQVdkbDFnTWRSUHduUm1FQzFVTVAzSHNaNG1nak4xSkdRSmtJOTVHYVEKOUZzajc1dmNoVFl4UmNkd2w1MEZlL1E0eHZEOXo0ZHlScU9oTDN5V2RPUy9UR2xIYytCQmErcWNzZ1FxL0ZieApVR3R6YldDZE9uUDJ2SEJRcVpuL3FKNDlwcjV6MnQxbVlnREFxVERwemk4Q0F3RUFBYU51TUd3d0NRWURWUjBUCkJBSXdBREFMQmdOVkhROEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3SXdQUVlEVlIwUkJEWXcKTklJZmQyVmlhRzl2YXkxelpYSjJaWEl1ZDJWaWFHOXZheTFrWlcxdkxuTjJZNElHZDI5eWEyVnlnZ2xzYjJOaApiR2h2YzNRd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGYkdBSjh1Wkl0UDVPWGptVHlWYnhTZVZzV3QyeGNVCkRPRWNNd3FFbkYxNDdQWnZRRWhNQXJpWXdPR2JKb2JvV0dHdVRtYkNaVEVzTUh1RUptNm9IRjFQbDc0WTNxRDEKQTRDTGMwRFBodDhBR3FrZnpnTEpsRDVUSnJNU2M0SWV1aUw5ZTRxNEFQSnFpS0xWVXcxbDR1dGN0WlBYdS94RgplRGFVazl6TmkwYXlOTkJtdGRic1lzeGJsV1I0Q0plNVpLYThjZE02OEE3ZVFtREszanF5ZHMwcGVpOFM3TnpPCllxT291amQySHA5blZ6aEZjS0dkenBteXZESzFLd2NuYlZRZ3diY2tjY3FPaGM2aXNjRVIxa1kzZytFVEFXeEwKS2NMR0RJOG4wZW9zU1R6L1Z3Y2w4aU5UbExxcCthVUt0YlNXMkRra3JlaXordFlHQk9UWGMxTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCYWcgQXR0cmlidXRlcwogICAgbG9jYWxLZXlJRDogRUEgQkYgMTkgRkEgODQgQzggQTAgRTIgOTQgMDMgNTIgNUQgNDQgQkEgOUMgOTggRUYgNzMgMTggMjAgCktleSBBdHRyaWJ1dGVzOiA8Tm8gQXR0cmlidXRlcz4KLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFp1ZGhwTDduNUdmWVQKUmxMMDgzV2d5QnBLakQveVpIdVk0cFBhY21yRXE2cmx4NmdIOENLdzIyU0RES0psT2sxT0QyWUxhOVhEdExzcgo0NWh0L2tYVkRCYVlvaldTSzhpbHVmdGI1b3NYbjM1bnQrMjh0cXE1NjlhY3NRRHlJWGdURXBUUWRHS2NmeS9yCk1zMDZLOVJtYm9sWU9iNlZwZU9Gd0I2UDR4UlIwb3crMVQ5c2VEcWp5Y0dLTHlFM2toSXJBRm5aZFlESFVUOEoKMFpoQXRWREQ5eDdHZUpvSXpkU1JrQ1pDUGVSbWtQUmJJKytiM0lVMk1VWEhjSmVkQlh2ME9NYncvYytIY2thagpvUzk4bG5Ua3YweHBSM1BnUVd2cW5MSUVLdnhXOFZCcmMyMWduVHB6OXJ4d1VLbVovNmllUGFhK2M5cmRabUlBCndLa3c2YzR2QWdNQkFBRUNnZ0VBWUk1U3N4TS9Yb0ZzNTg5Z0t0RnRjUWhNNEpLaUtWVDJteTZnYzFnYWtXMncKTkliK3RjYUJHLzJ2N1k1RTFxK3NhTm5iWDJWTFA2ZCsray9NNGJyS0xWbFhEQW1qeUZjeWZJeW1OSE5oYS9DSApsbWV6UHVXamdTQmQ1TTk2bytiRDRYRjBIWjMvdlhlS1FMd2UxNVZvZEtUQXRDZW5wYVlUNk5UeXVNenp6ZlRJClpYU3ZRY21YSHYrcEhMR3graEVSeGgvU3VGM3dDSm9QZVBkNko2b1p5M1B6bkU3SWxTZFg1eTR1bUQ0bUU1bHIKZkh1ODZMM3gxL2VEMCs1QmNidVJWT0twVHdPazFoaEtHeElsU0xXL0Q1Vm1uUzRKSVUyZklCTG9Rc0x4OWpHVQpEOCtRbGc2VSt5d3QxNUJjMm8zd0ZVZndJUGN4Qnd2UXBxdEJYei9oUVFLQmdRRHRuNHNDSVZ6V1NyR1pOdDk0CmZaN3pkUlBwYzlNaDYrQytrWmliQWJlWWJ2Wm9HN1hiUXl4alBJK0FXVEkwR081bVNuanRFMTdmQjBXZGhjYWoKZ293cHJMeCtGcVlQaEh1WTJ2WWRUMHZubTlETzdJN2VCc2FNYVVTRzN2dmFmM01jcVlTWlNXZHNmRTErQXBTKwpVakhFemdVaUc2KytrTlQxY1JQYkR2Y2xVd0tCZ1FEcWtHQ0pEcEhvQ3RGNjMweitQT3JwaER0SU91MHpkcWZqCkJoUUp1ZGhLU1hkaW1ZdlBTL0FibHNOdTloeERSem9pTTQ0YlhpL0RLYkd6a2kvdVUwdVFBTFFKMTU4WTdGNmMKKzhuY2RSR01MbE94cmQxaUVENE96c1NLZ1ZNSElCeUVmNWZlOXBlVlhsR1RoSUtYaXNyRUpXbTV3ak1UWFpQMgpwcTdISW00Y05RS0JnRGwySXo5WW9nS1AvWEozZW9MQW5mZHhrR2Nid3lxb3g2aE52UUYrNE03VHhuSldnUnVNCm11ZEVkYzhyd3FBbWh6L2xNbWppRGtjUWt4ME1oSVIxeFQ4dXJrWXZZK2pNdUxhMS9GNEtGdWpqSFJOczBQK1AKMCtPUWNTbk1Na3NjRnRJUGpDa2xQd1ZVNmNoWEIzRWVuenBnTjQyUDlHZTR6a2FzR1lrWGpWeFJBb0dCQUpBMgpoZk9lRHB6UWtleHVmK0xMeDA0YzYybkVPUFBzSHRwWWNWZHRlSXByMHNlL1NaTUF5RFhlSW5nRlBta3EwSllZCmhtVlRLaUJlY1EvTGNFYWgxWkpLckdaa3VEOVZpL0lPYUJSdnNZTXpOR2ZJVXBVcEVVNS9WNTBrVjh6SXRGL08KSnF5QmhiN2pCMXFnSEw1WktjTWdrWGtRNmVBZEo0eDgvSFlZT0FTRkFvR0JBS0VYKzFUTnVaUjhXdHZTcFd0dgo4RzBMbThMRm9WZzVPbWMxVDNDZ3ZMMkhaQk9udlpzQkFzTXpZQTVrd1M5WlV0WTRpUmtpeWxzWnc3emZBVkg1CjN2YmFjQkpEcmtSemlxdk1CSVZLNm9jYmZ3dHlhNVMvZWMxQ3grWlIrWjZIc205MHZURGlGQzA4R3JHckdjTEoKVXVjYW1TUkppVkJRaitGdkJxZjJOTTBQCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lKQU5vV1orOWw4TGhvTUEwR0NTcUdTSWIzRFFFQkN3VUFNREV4SURBZUJnTlYKQkFNTUYxUk1VMGRsYmxObGJHWlRhV2R1WldSMFVtOXZkRU5CTVEwd0N3WURWUVFIREFRa0pDUWtNQjRYRFRJdwpNRGt4TlRJeE1ERXlNRm9YRFRNd01Ea3hNekl4TURFeU1Gb3dNVEVnTUI0R0ExVUVBd3dYVkV4VFIyVnVVMlZzClpsTnBaMjVsWkhSU2IyOTBRMEV4RFRBTEJnTlZCQWNNQkNRa0pDUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRREhFU0V1dFdRYnNTSnkrZm41K0toekE5T0p1TGNxcTVPOVpGOWVJc1g2WERJcApHOXoxaEMxNForOXByZ2NYaCtkTm03enNWaHJvT0d1K3N1UzU4QXozN1pWTlpYTkF0aStrNjNNYTdnMXBTU3dLCjBFZVR0czVrWVQyeEFCYzBmNDBWVHZ5UHBlMmZ4YzhOMjBnRFBzdWR6WkYrNlRRaCt1ZmhXUE5HY3NxQy9PcHoKaGdhVmVkZkFsUzFuWmQyTzc2M3JtdzNoOUp5OXRPYzdNY0xWYUt6dkUycmppbTVRYThmdUdTQ0drU3lqZEJOagp2MjE1TUlHWXd4UEg0STg3U0wyeml5WTJiSTUxdktOOUVadjFyamNhRVdqOHVFdzFHSFM4QmE1aGt6QzJjb1JZCkpwaUV2cE1SM0oweVdFT3Z2MytTcHF4SEhyNDdMMUF5TXp5WWJGQ1JBZ01CQUFHallEQmVNQXNHQTFVZER3UUUKQXdJQkJqQWRCZ05WSFE0RUZnUVUyRzRrWHpaNG1kbXB0Z1cxenp1Ump6bURpZm93SHdZRFZSMGpCQmd3Rm9BVQoyRzRrWHpaNG1kbXB0Z1cxenp1Ump6bURpZm93RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQUQ4cTdXTTBad2d2b3k4dnBWY25TUjIvMFFLc1ArbTFURVp3Y3dacFRvR21vMUNHdHF2TkIKR3VWb1lBUXN2WmxmNEtueHZXWGJvcVBhNGVteWJndGJQUVcvdWRwN2dVK0JTcmI3R2xHZGhtSTVHclI2Rmh5dgptT3JWNytsYkdHMmU5U3NHanNpY25lZVJ4TGVxdVhVTzNHYXp6Z0xGRmZuaGJJc1VUUHVqLzNOQUp1UStZN3haCm8zSzM5N1J1alRXZnV6TjByQlZZSWI5TnBFQ2hqcUcwKzlHOHVzU2lBdW55NDcyallzZWpYQVN2MUxhQjVGTzMKeHFWWEpudTduaWtuSFFncE1wT2ZBeHZzVlVkYmtQWGxHcXlJSFFBdHVtT3BoQVdwY20wWUhKZ3R2QUEwTTFBbQpCZ0szVEFNWTZuUGhDYWdjblF2aUF0REtjc256ODZzQjd3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
